config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'pages#index'


  get 'chancekirby', to: 'pages#chancekirby', as: 'chancekirby'

  get 'NaitikKaythwal', to: 'pages#NaitikKaythwal', as: 'NaitikKaythwal'
  get 'robomal', to: 'pages#robomal', as: 'robomal'

  get 'uofmmk', to: 'pages#uofmmk', as: 'uofmmk'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end



  def chancekirby
  end
  

  def robomal
  end


  def NaitikKaythwal
  end

  def uofmmk
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamCollab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/NaitikKaythwal.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Me</title>
</head>
<body>
    <div class="container">
        <h1>Things About Me</h1>
        <p>Hello, I'm Naitik. Here's a little bit about myself:</p>
        <ul>
            <li>I'm an international undergrad at UofM.</li>
            <li>I'm majoring in CS and Math and a minor in Finance</li>
            <li>I'm set th graduate in Spring 2024</li>
            <li>I'm also applying for a masters at UofM starting </li>
            <li>In my free time, I enjoy playing games and listening to music or watching movies and tv shows.</li>
        </ul>
        <p>Feel free to reach out to me at <a href="mailto:nkythwal@memphis.edu">nkythwal@memphis.edu</a> or connect with me on <a href="https://www.linkedin.com/in/naitik-kaythwal-057347202/">LinkedIn</a></p>
    </div>
</body>
</html>

app/views/pages/RoboMal.html.erb
<h1>Malcolm King</h1>
<p>Facts:</p>
<ul>
    <li>I like pie</li>
    <li>I once beat a snake in a staring contest</li>
    <li>I would recommend sprinting diretly toward home intruders</li>
    <li>I am apathetic toward sand</li>
    <li>If I could make 1 wish with the 7 Dragon Balls, I would wish for the ability to sleep soundly on-command</li>
</ul>

app/views/pages/chancekirby.html.erb
<h1>About Me</h1>

<p>
My name is Chance Kirby, and I am a junior Computer Science major concentrating in artificial intelligence.
</p>

app/views/pages/index.html.erb
<h1>Directory of Student Pages</h1>

<ul>


    <li><%= link_to 'chancekirby', chancekirby_path %></li>


    <li><%= link_to 'NaitikKaythwal', NaitikKaythwal_path %></li>

    <li><%= link_to 'uofmmk', uofmmk_path %></li>

    <li><%= link_to 'RoboMal', username_path %></li>
</ul>

app/views/pages/uofmmk.html.erb
<h1>Michael Kingma </h1>
<table class="table table-hover">
  <thead class="table-dark">
    <tr>
      <th>Major: Computer Science</th>
      <th>Concentration: Cyber Security</th>
    </tr>
  </thead>